import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const SCRIPTS_ROOT = path.join(ROOT, "public", "scripts");
const DATA_DIR = path.join(ROOT, "src", "data");

// Which categories to scan and their export variable names
const CATEGORY_CONFIG = {
  Lab: { export: "labProjects" },
  Builds: { export: "builds" },
  Thoughts: { export: "thoughts" },
  Tools: { export: null }, // group-based: exports derived from meta.json `group` field
};

/**
 * Extract the title from the first `text("# ...")` heading in the .py file.
 */
function extractTitle(pyContent) {
  const match = pyContent.match(/text\("#\s*([^"]+)"\)/);
  if (match) return match[1].trim();
  return null;
}

/**
 * Extract the module docstring (first `"""..."""` block) as description.
 * Handles both single-line and multi-line docstrings.
 */
function extractDescription(pyContent) {
  // Match from first """ to the closing """ — handles multi-line
  const match = pyContent.match(/^"""(.*?)"""/s);
  if (match) {
    return match[1]
      .trim()
      .replace(/\n\s*/g, " ") // collapse newlines to single space
      .replace(/\s+/g, " ")
      .substring(0, 300);
  }
  return "";
}

/**
 * Derive a human-readable title from a kebab-case slug.
 */
function slugToTitle(slug) {
  return slug
    .split("-")
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(" ");
}

/**
 * Format a ContentItem object as a TypeScript object literal.
 */
function formatItem(item, indent = 2) {
  const p = " ".repeat(indent);
  const lines = [];
  lines.push(`${p}{`);
  lines.push(`${p}  slug: ${JSON.stringify(item.slug)},`);
  lines.push(`${p}  title: ${JSON.stringify(item.title)},`);
  lines.push(`${p}  description:`);
  lines.push(`${p}    ${JSON.stringify(item.description)},`);
  lines.push(`${p}  date: ${JSON.stringify(item.date)},`);
  lines.push(`${p}  tags: [${item.tags.map((t) => JSON.stringify(t)).join(", ")}],`);
  if (item.status) lines.push(`${p}  status: ${JSON.stringify(item.status)},`);
  if (item.demo) lines.push(`${p}  demo: ${JSON.stringify(item.demo)},`);
  if (item.subtitle) lines.push(`${p}  subtitle: ${JSON.stringify(item.subtitle)},`);
  if (item.readingTime != null) lines.push(`${p}  readingTime: ${item.readingTime},`);
  lines.push(`${p}},`);
  return lines.join("\n");
}

/**
 * Process one category directory: scan subdirectories, read meta.json + .py,
 * return sorted ContentItem array.
 */
function processCategory(category) {
  const dir = path.join(SCRIPTS_ROOT, category);
  if (!fs.existsSync(dir)) return [];

  const items = [];

  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue;

    const slug = entry.name;
    const pyFile = path.join(dir, slug, `${slug}.py`);
    const metaFile = path.join(dir, slug, "meta.json");

    // Skip directories without a matching .py file
    if (!fs.existsSync(pyFile)) {
      console.warn(
        `  ⚠  ${category}/${slug}: no ${slug}.py found, skipping`
      );
      continue;
    }

    // meta.json is required for date and tags
    if (!fs.existsSync(metaFile)) {
      console.error(
        `  ✗  ${category}/${slug}: meta.json is required (date + tags)`
      );
      process.exit(1);
    }

    const pyContent = fs.readFileSync(pyFile, "utf-8");
    let meta;
    try {
      meta = JSON.parse(fs.readFileSync(metaFile, "utf-8"));
    } catch (e) {
      console.error(
        `  ✗  ${category}/${slug}: invalid meta.json — ${e.message}`
      );
      process.exit(1);
    }

    if (!meta.date) {
      console.error(
        `  ✗  ${category}/${slug}: meta.json missing required field: date`
      );
      process.exit(1);
    }
    if (!meta.tags || !Array.isArray(meta.tags)) {
      console.error(
        `  ✗  ${category}/${slug}: meta.json missing required field: tags`
      );
      process.exit(1);
    }

    const title = meta.title || extractTitle(pyContent) || slugToTitle(slug);
    const description = meta.description || extractDescription(pyContent) || "";

    items.push({
      slug,
      title,
      description: description.substring(0, 300),
      date: meta.date,
      tags: meta.tags,
      status: meta.status,
      demo: meta.demo,
      subtitle: meta.subtitle,
      readingTime: meta.readingTime,
      group: meta.group,
    });

    console.log(`  ✓  ${category}/${slug}`);
  }

  // Sort newest-first
  items.sort((a, b) => b.date.localeCompare(a.date));
  return items;
}

/**
 * Write a generated .ts data file.
 */
function writeDataFile(category, items) {
  const tsPath = path.join(DATA_DIR, `${category.toLowerCase()}.ts`);
  let content = `// Auto-generated by scripts/generate-data.mjs — DO NOT EDIT manually.\n`;
  content += `// Run: node scripts/generate-data.mjs\n`;
  content += `import type { ContentItem } from "@/lib/types";\n\n`;

  if (category === "Tools") {
    // Group items by their `group` field for separate exports
    const groups = {};
    for (const item of items) {
      const grp = item.group || "tools";
      delete item.group;
      if (!groups[grp]) groups[grp] = [];
      groups[grp].push(item);
    }
    for (const [groupName, groupItems] of Object.entries(groups)) {
      content += `export const ${groupName}: ContentItem[] = [\n`;
      for (const item of groupItems) {
        content += formatItem(item) + "\n";
      }
      content += `];\n\n`;
    }
  } else {
    const exportName = CATEGORY_CONFIG[category].export;
    content += `export const ${exportName}: ContentItem[] = [\n`;
    for (const item of items) {
      content += formatItem(item) + "\n";
    }
    content += `];\n`;
  }

  fs.writeFileSync(tsPath, content, "utf-8");
  console.log(`  → wrote ${tsPath} (${items.length} items)`);
}

// ─── Main ────────────────────────────────────────────────────────────────────

console.log("Generating data files from public/scripts/...\n");

for (const category of Object.keys(CATEGORY_CONFIG)) {
  console.log(`${category}:`);
  const items = processCategory(category);
  if (items.length > 0) {
    writeDataFile(category, items);
  } else {
    console.log(`  (no projects found)`);
  }
  console.log();
}

console.log("Done.");
