// Auto-generated by scripts/generate-data.mjs — DO NOT EDIT manually.
// Run: node scripts/generate-data.mjs
import type { ContentItem } from "@/lib/types";

export const labProjects: ContentItem[] = [
  {
    slug: "proposal-generation-platform",
    title: "proposal generation platform",
    description:
      "This experimental project was built to test a cutting-edge Design-to-Code workflow using Claude Code. It delivers a streamlined, asynchronous full-stack SaaS platform that automates the entire B2B sales pipeline from a raw text description to a beautifully templated proposal, all the way to final ch",
    date: "2026-06",
    tags: ["Claude Code", "Design-to-Code", "AI Workflow"],
    status: "archived",
  },
  {
    slug: "place-holder",
    title: "place holder",
    description:
      "",
    date: "2026-05",
    tags: ["Python", "RAG", "LlamaIndex"],
    status: "active",
  },
];
