// Auto-generated by scripts/generate-data.mjs — DO NOT EDIT manually.
// Run: node scripts/generate-data.mjs
import type { ContentItem } from "@/lib/types";

export const resources: ContentItem[] = [
  {
    slug: "current-reading",
    title: "code: the hidden language of computer hardware and software",
    description:
      "Instead of bombarding the reader with dry circuits or abstract math, this book elegantly traces the historical and engineering lineage of how computers actually work.",
    date: "2026-07",
    tags: ["Reading", "Books", "Learning"],
    status: "active",
    image: "https://upload.wikimedia.org/wikipedia/en/7/7f/Code_The_Hidden_Language_of_Computer_Hardware_and_Software.jpg",
  },
];
