// Auto-generated by scripts/generate-data.mjs — DO NOT EDIT manually.
// Run: node scripts/generate-data.mjs
import type { ContentItem } from "@/lib/types";

export const resources: ContentItem[] = [
  {
    slug: "resources",
    title: "Current Reading",
    description:
      "Books, papers, and articles I'm currently reading and recommending.",
    date: "2026-07",
    tags: ["Reading", "Books", "Learning"],
    status: "active",
  },
];
