// Auto-generated by scripts/generate-data.mjs — DO NOT EDIT manually.
// Run: node scripts/generate-data.mjs
import type { ContentItem } from "@/lib/types";

export const thoughts: ContentItem[] = [
  {
    slug: "on-building-in-public",
    title: "place-holder",
    description:
      "",
    date: "2026-06-15",
    tags: ["Reflection", "Building"],
    readingTime: 8,
  },
  {
    slug: "notes-on-rust-vs-go",
    title: "place-holder",
    description:
      "",
    date: "2026-05-20",
    tags: ["Rust", "Go", "Engineering"],
    readingTime: 12,
  },
  {
    slug: "the-case-for-static-sites",
    title: "place-holder",
    description:
      "",
    date: "2026-04-10",
    tags: ["Web", "Architecture"],
    readingTime: 6,
  },
];
