// Auto-generated by scripts/generate-data.mjs — DO NOT EDIT manually.
// Run: node scripts/generate-data.mjs
import type { ContentItem } from "@/lib/types";

export const claudeCodeTools: ContentItem[] = [
  {
    slug: "claude-code-tool",
    title: "place-holder",
    description:
      "",
    date: "2026-06",
    tags: ["AI", "Developer Tools"],
    subtitle: "Agentic coding tool",
  },
];

export const llmTools: ContentItem[] = [
  {
    slug: "llm-orchestrator",
    title: "place-holder",
    description:
      "",
    date: "2026-05",
    tags: ["LLM", "Orchestration", "Python"],
    subtitle: "Multi-model workflow engine",
  },
];

